language: clojure
lein: lein2

jdk:
  - openjdk7
  - oraclejdk7

install:
  - sudo apt-get install -qq socat

script:
  lein test

branches:
  only: master

notifications:
  email:
    on_success: never
